/* Create DB*/

CREATE DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UserManagementDatabase', FILENAME = N'C:\Code\Coink\UserManagement\src\UserManagement.Data\UserManagementDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UserManagementDatabase_log', FILENAME = N'C:\Code\Coink\UserManagement\src\UserManagement.Data\UserManagementDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET ARITHABORT OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET  ENABLE_BROKER 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET  MULTI_USER 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET DB_CHAINING OFF 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET QUERY_STORE = OFF
GO

USE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [C:\CODE\COINK\USERMANAGEMENT\SRC\USERMANAGEMENT.DATA\USERMANAGEMENTDATABASE.MDF] SET  READ_WRITE 
GO

/* Create Countries Table*/

CREATE TABLE [dbo].[Countries](
	[CountryId] [int] NOT NULL,
	[Code] [nvarchar](max) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Countries] PRIMARY KEY CLUSTERED 
(
	[CountryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

INSERT INTO [dbo].[Countries]
           ([CountryId]
           ,[Code]
           ,[Name])
     VALUES
           (1
           ,'CO'
           ,'Colombia')
GO

/* Create States Table*/

CREATE TABLE [dbo].[States](
	[StateId] [int] NOT NULL,
	[Code] [nvarchar](max) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[CountryId] [int] NOT NULL,
 CONSTRAINT [PK_States] PRIMARY KEY CLUSTERED 
(
	[StateId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[States]  WITH CHECK ADD  CONSTRAINT [FK_States_Countries_CountryId] FOREIGN KEY([CountryId])
REFERENCES [dbo].[Countries] ([CountryId])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[States] CHECK CONSTRAINT [FK_States_Countries_CountryId]
GO

INSERT INTO [dbo].[States]
           ([StateId]
           ,[Code]
           ,[Name]
           ,[CountryId])
     VALUES
           (1
           ,'ANT'
           ,'Antioquia'
           ,1)
GO

INSERT INTO [dbo].[States]
           ([StateId]
           ,[Code]
           ,[Name]
           ,[CountryId])
     VALUES
           (2
           ,'CU'
           ,'Cundinamarca'
           ,1)
GO

/* Create Cities Table*/

CREATE TABLE [dbo].[Cities](
	[CityId] [int] NOT NULL,
	[Code] [nvarchar](max) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[StateId] [int] NOT NULL,
 CONSTRAINT [PK_Cities] PRIMARY KEY CLUSTERED 
(
	[CityId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Cities]  WITH CHECK ADD  CONSTRAINT [FK_Cities_States_StateId] FOREIGN KEY([StateId])
REFERENCES [dbo].[States] ([StateId])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Cities] CHECK CONSTRAINT [FK_Cities_States_StateId]
GO

INSERT INTO [dbo].[Cities]
           ([CityId]
           ,[Code]
           ,[Name]
           ,[StateId])
     VALUES
           (1
           ,'MED'
           ,'Medellín'
           ,1)
GO

INSERT INTO [dbo].[Cities]
           ([CityId]
           ,[Code]
           ,[Name]
           ,[StateId])
     VALUES
           (2
           ,'BOG'
           ,'Bogota'
           ,2)
GO

/* Create Users Table*/

CREATE TABLE [dbo].[Users](
	[UserId] [int] NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[PhoneNumber] [nvarchar](max) NOT NULL,
	[Address] [nvarchar](max) NOT NULL,
	[CityId] [int] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [FK_Users_Cities_CityId] FOREIGN KEY([CityId])
REFERENCES [dbo].[Cities] ([CityId])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [FK_Users_Cities_CityId]
GO